In [1]:
# X is area in sqft,y is price in INR table
x = [[1000],[1200],[1500]]
y = [60,90,100]

In [2]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [3]:
model.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [4]:
model.predict([[500]])

array([27.36842105])

In [5]:
model.predict([[2500],[1800]])

array([180.        , 126.57894737])

In [6]:
model.coef_ # a value

array([0.07631579])

In [7]:
model.intercept_ # b value

-10.789473684210549

In [8]:
# import necessary packages
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score # model fitment efficiency

In [9]:
# Load the data
data = pd.read_csv("hp_data.csv")
data.head()

place                 built  sqft    sale  yearsOld  floor  \
0  BTM Layout  Super built-up  Area  1450  Resale         5      1   
1   Yelahanka  Super built-up  Area  2190  Resale         5      3   
2  Whitefield  Super built-up  Area  1019  Resale         1      2   
3  Ambalipura  Super built-up  Area  1857  Resale        15      4   
4   Yelahanka  Super built-up  Area  2190  Resale         5      3   

   totalFloor  bhk     price  
0           4    1   6300000  
1           5    3  11500000  
2           5    2   3800000  
3           5    4  10500000  
4           5    3  11500000

In [10]:
# Basic checks
data.shape

(3500, 9)

In [11]:
data.isnull().sum()

place         0
built         0
sqft          0
sale          0
yearsOld      0
floor         0
totalFloor    0
bhk           0
price         0
dtype: int64

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3500 entries, 0 to 3499
Data columns (total 9 columns):
place         3500 non-null object
built         3500 non-null object
sqft          3500 non-null int64
sale          3500 non-null object
yearsOld      3500 non-null int64
floor         3500 non-null int64
totalFloor    3500 non-null int64
bhk           3500 non-null int64
price         3500 non-null int64
dtypes: int64(6), object(3)
memory usage: 246.2+ KB


In [13]:
# definine x and Y
X = data.loc[:,['sqft','yearsOld','floor']]
y = data.price

In [14]:
# Train-Test Split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25)

In [15]:
# Define model
model = LinearRegression()
model.fit(X_train,y_train) #Training

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [16]:
# Predict
y_predict = model.predict(X_test)

In [17]:
r2_score(y_test,y_predict) # model fitment efficiency It means how the model is doing

0.6106741947494676

# Predict Mileage for mtcars dataset
Independent Variables - hp,am,wt
Dependent Cariable - mpg

In [21]:
data2 = pd.read_csv("mtcars.csv")
data2.head()
X2 = data2.loc[:,['hp','am','wt']]
y2 = data2.mpg

In [29]:
# Train-Test Split
X2_train,X2_test,y2_train,y2_test = train_test_split(X2,y2,test_size=0.25,random_state=5)

In [30]:
# Define model
model = LinearRegression()
model.fit(X2_train,y2_train) #Training

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [31]:
# Predict
y2_predict = model.predict(X2_test)
y2_predict

array([18.89664109, 26.39006234, 23.28921242, 19.38368628, 16.06146668,
       22.69820125, 16.10962483, 27.20786536])

In [32]:
r2_score(y_test,y_predict) # model fitment efficiency It means how the model is doing

0.6106741947494676